# Generated by Django 3.0.5 on 2020-05-03 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='instructions',
            field=models.TextField(default='Instruction coming soon.'),
        ),
    ]
