# Generated by Django 3.0.5 on 2020-05-03 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_recipe_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='imageUrl',
            field=models.TextField(default=''),
        ),
    ]
