[tool.poetry]
name = "recipe-v1"
version = "0.1.0"
description = ""
authors = ["Binup karki <karki011@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
django = "^3.0.14"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
